# This file was generated by GoReleaser. DO NOT EDIT.
$ErrorActionPreference = 'Stop';

$version = $env:chocolateyPackageVersion
$packageName = $env:chocolateyPackageName
$toolsDir = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"

$packageArgs = @{
    packageName    = $packageName
    unzipLocation  = $toolsDir
    url64bit       = 'https://github.com/metaplay/cli/releases/download/1.6.1/MetaplayCLI_Windows_x86_64.zip'
    checksum64     = '93c5f271853f35b36feed38d3b078ffff62735ec3d3e41f7a2223c5d32b3094a'
    checksumType64 = 'sha256'
}

Install-ChocolateyZipPackage @packageArgs
