# This file was generated by GoReleaser. DO NOT EDIT.
$ErrorActionPreference = 'Stop';

$version = $env:chocolateyPackageVersion
$packageName = $env:chocolateyPackageName
$toolsDir = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"

$packageArgs = @{
    packageName    = $packageName
    unzipLocation  = $toolsDir
    url64bit       = 'https://github.com/metaplay/cli/releases/download/1.3.1/MetaplayCLI_Windows_x86_64.zip'
    checksum64     = '365e1cdc70a4a1eaf2eb181b04ed27b34f0f7c9782132a11d72f2d613b1d9660'
    checksumType64 = 'sha256'
}

Install-ChocolateyZipPackage @packageArgs
