# This file was generated by GoReleaser. DO NOT EDIT.
$ErrorActionPreference = 'Stop';

$version = $env:chocolateyPackageVersion
$packageName = $env:chocolateyPackageName
$toolsDir = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"

$packageArgs = @{
    packageName    = $packageName
    unzipLocation  = $toolsDir
    url64bit       = 'https://github.com/metaplay/cli/releases/download/1.9.2/MetaplayCLI_Windows_x86_64.zip'
    checksum64     = '1523a166a957c48ec6df5af06cf1b09cda41eaf4c8530a1d5aac47c636649061'
    checksumType64 = 'sha256'
}

Install-ChocolateyZipPackage @packageArgs
